apiVersion: rbac.authorization.k8s.io/v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    labels:
      app.kubernetes.io/instance: conprof
      app.kubernetes.io/name: conprof
      app.kubernetes.io/version: master-2020-04-09-4ec33b8
    name: conprof
    namespace: conprof
  rules:
  - apiGroups:
    - ""
    resources:
    - services
    - endpoints
    - pods
    verbs:
    - get
    - list
    - watch
kind: RoleList
