apiVersion: v1
data: {}
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: conprof
    app.kubernetes.io/name: conprof
    app.kubernetes.io/version: master-2020-04-09-4ec33b8
  name: conprof-config
  namespace: conprof
stringData:
  conprof.yaml: |-
    "scrape_configs":
    - "job_name": "conprof"
      "kubernetes_sd_configs":
      - "namespaces":
          "names":
          - "conprof"
        "role": "pod"
      "relabel_configs":
      - "action": "keep"
        "regex": "conprof.*"
        "source_labels":
        - "__meta_kubernetes_pod_name"
      - "source_labels":
        - "__meta_kubernetes_namespace"
        "target_label": "namespace"
      - "source_labels":
        - "__meta_kubernetes_pod_name"
        "target_label": "pod"
      - "source_labels":
        - "__meta_kubernetes_pod_container_name"
        "target_label": "container"
      "scrape_interval": "1m"
      "scrape_timeout": "1m"
type: Opaque
