name: go

on:
  push:
    branches:
      - master
    tags:
  pull_request:

jobs:
  cross-build-check:
    runs-on: ubuntu-latest
    name: Build artifacts for various platforms
    env:
      GOBIN: /tmp/.bin
    steps:
      - name: Install Go.
        uses: actions/setup-go@v1
        with:
          go-version: 1.15.x

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Cross build check.
        run: make crossbuild

      - name: Login to DockerHub
        uses: docker/login-action@v1
        #if: "if: github.ref == 'refs/heads/master'"
        with:
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Build and publish docker images
        #if: "if: github.ref == 'refs/heads/master'"
        run: DOCKER_IMAGE_TAG="$(git rev-parse --abbrev-ref HEAD | tr / -)-$(date +%Y-%m-%d)-$(git rev-parse --short HEAD)" make common-docker #common-docker-tag-latest common-docker-publish common-docker-manifest
  lint:
    runs-on: ubuntu-latest
    name: Linters (Static Analysis) for Go
    env:
      GOBIN: /tmp/.bin
    steps:
      - name: Checkout code into the Go module directory.
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x

      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Format.
        run: make format

      - name: Linting & vetting.
        run: make lint
  e2e:
    runs-on: ubuntu-latest
    name: end-to-end tests
    env:
      GOBIN: /tmp/.bin
    steps:
      - name: Install Go.
        uses: actions/setup-go@v1
        with:
          go-version: 1.15.x

      - name: Check out code into the Go module directory.
        uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Run e2e docker-based tests.
        run: make test-e2e
  test-unit:
    runs-on: ubuntu-latest
    name: unit tests
    env:
      GOBIN: /tmp/.bin
    steps:
      - name: Install Go.
        uses: actions/setup-go@v1
        with:
          go-version: 1.15.x

      - name: Check out code into the Go module directory.
        uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Run e2e docker-based tests.
        run: make test
